# Site settings
theme: jekyll-theme-primer
title: 'Course Organization System'
description: 'This Google Apps Script suite automates course data standardization within Google Sheets for academic entities.'
